package com.cloud.cache.daos;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cloud.cache.StackInfoItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "rx_cache_stack_info".
*/
public class StackInfoItemDao extends AbstractDao<StackInfoItem, String> {

    public static final String TABLENAME = "rx_cache_stack_info";

    /**
     * Properties of entity StackInfoItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Key = new Property(0, String.class, "key", true, "key");
        public final static Property Stack = new Property(1, String.class, "stack", false, "stack");
        public final static Property Code = new Property(2, int.class, "code", false, "code");
        public final static Property Protocol = new Property(3, String.class, "protocol", false, "protocol");
        public final static Property Headers = new Property(4, String.class, "headers", false, "HEADERS");
        public final static Property Params = new Property(5, String.class, "params", false, "PARAMS");
        public final static Property RequestType = new Property(6, String.class, "requestType", false, "REQUEST_TYPE");
        public final static Property Url = new Property(7, String.class, "url", false, "URL");
        public final static Property Message = new Property(8, String.class, "message", false, "MESSAGE");
    }


    public StackInfoItemDao(DaoConfig config) {
        super(config);
    }
    
    public StackInfoItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"rx_cache_stack_info\" (" + //
                "\"key\" TEXT PRIMARY KEY NOT NULL ," + // 0: key
                "\"stack\" TEXT," + // 1: stack
                "\"code\" INTEGER NOT NULL ," + // 2: code
                "\"protocol\" TEXT," + // 3: protocol
                "\"HEADERS\" TEXT," + // 4: headers
                "\"PARAMS\" TEXT," + // 5: params
                "\"REQUEST_TYPE\" TEXT," + // 6: requestType
                "\"URL\" TEXT," + // 7: url
                "\"MESSAGE\" TEXT);"); // 8: message
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_rx_cache_stack_info_key ON \"rx_cache_stack_info\"" +
                " (\"key\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"rx_cache_stack_info\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StackInfoItem entity) {
        stmt.clearBindings();
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(1, key);
        }
 
        String stack = entity.getStack();
        if (stack != null) {
            stmt.bindString(2, stack);
        }
        stmt.bindLong(3, entity.getCode());
 
        String protocol = entity.getProtocol();
        if (protocol != null) {
            stmt.bindString(4, protocol);
        }
 
        String headers = entity.getHeaders();
        if (headers != null) {
            stmt.bindString(5, headers);
        }
 
        String params = entity.getParams();
        if (params != null) {
            stmt.bindString(6, params);
        }
 
        String requestType = entity.getRequestType();
        if (requestType != null) {
            stmt.bindString(7, requestType);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(8, url);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(9, message);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StackInfoItem entity) {
        stmt.clearBindings();
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(1, key);
        }
 
        String stack = entity.getStack();
        if (stack != null) {
            stmt.bindString(2, stack);
        }
        stmt.bindLong(3, entity.getCode());
 
        String protocol = entity.getProtocol();
        if (protocol != null) {
            stmt.bindString(4, protocol);
        }
 
        String headers = entity.getHeaders();
        if (headers != null) {
            stmt.bindString(5, headers);
        }
 
        String params = entity.getParams();
        if (params != null) {
            stmt.bindString(6, params);
        }
 
        String requestType = entity.getRequestType();
        if (requestType != null) {
            stmt.bindString(7, requestType);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(8, url);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(9, message);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public StackInfoItem readEntity(Cursor cursor, int offset) {
        StackInfoItem entity = new StackInfoItem( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // key
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // stack
            cursor.getInt(offset + 2), // code
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // protocol
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // headers
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // params
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // requestType
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // url
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // message
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StackInfoItem entity, int offset) {
        entity.setKey(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStack(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCode(cursor.getInt(offset + 2));
        entity.setProtocol(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setHeaders(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setParams(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRequestType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUrl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setMessage(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(StackInfoItem entity, long rowId) {
        return entity.getKey();
    }
    
    @Override
    public String getKey(StackInfoItem entity) {
        if(entity != null) {
            return entity.getKey();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StackInfoItem entity) {
        return entity.getKey() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
